Feature TT-3282 Add introspection resolver
TykTechnologies/graphql-go-tools pull request #178
Opened 2021-11-17 17:12 UTC by spetrunin

2021-11-18 11:12 UTC, jensneuse commented on pkg/engine/datasource/introspection_datasource/source.go
> +	switch req.RequestType {
What happens if a request contains multiple root fields with different Queries? e.g. requesting two type fields or type fields and schema?

2021-11-30 13:34 UTC, pvormste requested changes

2021-11-30 13:34 UTC, pvormste commented on pkg/ast/ast_root_operation_type_definition.go
> +			OfType:   -1,
I still think we should reuse the constant we already have for this magic number :-)

2021-11-30 13:34 UTC, pvormste commented on pkg/astparser/parser.go
> +					OfType:   -1,
Again magic number

2021-11-30 13:34 UTC, pvormste commented on pkg/engine/datasource/introspection_datasource/planner.go
> +	v                 *plan.Visitor
I think I would have guessed `visitor` with `v` ... but why not make it really clear and write it out? :-)

2021-12-08 11:50 UTC, merged