[TT-5279] Shared type, extension orphan and validation clean up
TykTechnologies/graphql-go-tools pull request #261
Opened 2022-05-13 16:26 UTC by Aenimus

[changelog]
internal: Shared types cannot be extended; added unique union member validation; unresolved extension orphans in the supergraph return an error

2022-05-13 16:27 UTC, Aenimus commented on pkg/federation/sdlmerge/check_extension_orphans.go
> +	//operation.DeleteRootNodes(operation.Index.MergedTypeExtensions)
Will delete this

2022-05-13 16:28 UTC, Aenimus commented on pkg/federation/sdlmerge/sdlmerge_test.go
> +	//t.Run("should merge product and review sdl and leave `extend type User` in the schema", runMergeTest(
Not sure how to handle this. Why did Cherom think it should be valid?

2022-05-13 16:31 UTC, Aenimus commented on pkg/federation/sdlmerge/object_type_extending.go
> +	shouldReturn := isQueryOrMutation(nameBytes)
I'm not sure how else we avoid tripping over queries and mutations (and whether there are other edge cases), but here is a possible solution.

2022-05-19 23:54 UTC, Aenimus commented on pkg/astvalidation/rule_populated_type_bodies.go
> +func isRootType(nameBytes []byte) bool {
This is a temporary solution

2022-05-25 08:33 UTC, pvormste requested changes

2022-05-25 08:33 UTC, pvormste commented on pkg/astvalidation/definition_validation.go
> +	return length == 5 && b[0] == 'Q' && b[1] == 'u' && b[2] == 'e' && b[3] == 'r' && b[4] == 'y'
I would suggest to create some constants in the `ast` package like this:
```go
const DefaultQueryTypeName = "Query"
const DefaultMutationTypeName = "Mutation"
const DefaultSubscriptionTypeName = "Subscription"
```

... and use those for comparison. You could also use them to remove some hardcoded values in `ast` package:
https://github.com/TykTechnologies/graphql-go-tools/blob/master/pkg/ast/ast_root_operation_type_definition.go#L54

2022-05-25 08:33 UTC, pvormste commented on pkg/astvalidation/rule_populated_type_bodies.go
> +			if length < 2 || fieldNameBytes[0] != '_' || fieldNameBytes[1] != '_' {
maybe it makes sense to create a helper function for this, there is also another rule checking for reserved type names: https://github.com/TykTechnologies/graphql-go-tools/blob/master/pkg/astvalidation/rule_unique_field_definition_names.go#L119

(maybe there are even more?)

2022-05-25 13:16 UTC, pvormste approved these changes

2022-05-26 08:56 UTC, Aenimus commented
/release to release-4

2022-05-26 09:04 UTC, spetrunin commented on pkg/federation/sdlmerge/interface_type_extending.go
> +	document := e.document
a bit unclear why do u need this var?

2022-05-26 09:38 UTC, Aenimus commented on pkg/federation/sdlmerge/interface_type_extending.go
> +	document := e.document
I call e.document 3 or 4 times

2022-05-26 11:02 UTC, spetrunin approved these changes

2022-05-26 11:04 UTC, merged